# Secret holds information about root password
---
apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: mariadb
type: Opaque
data:
  mariadb-root-password: c2VjcmV0 # echo -n 'secret'|base64

