apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mysql
spec:
  storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
   - ReadWriteOnce
  capacity:
    storage: 512M
  hostPath:
    path: /var/lib/mysql
  claimRef:
    name: mysql-pvc
    namespace: mysql
  