apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql-pod
