api:
  dashboard: false

entryPoints:
  websecure:
    address: ":443"
  ssh:
    address: ":22"

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    constraints: "Label(`traefik.constraint`, `gitea`)"
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO
