apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  nginx.conf: |
    server {
        listen 80;
        server_name app.example.com;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
